image: node:latest
stages:
  - test
services:
  - mysql:5.7
variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: '1'
  MYSQL_DATABASE: onduka_db_test
  JWT_KEY_KEY: $JWT_KEY_KEY
  DB_HOST_TEST: $DB_HOST_TEST
  DB_PASSWORD_TEST: $DB_PASSWORD_TEST
  DB_USER_TEST: $DB_USER_TEST
  DB_NAME_TEST: db
  BASE_URL: $BASE_URL
  FACEBOOK_APP_SECRET: $FACEBOOK_APP_SECRET
  FACEBOOK_APP_ID: $FACEBOOK_APP_ID
  DOMAIN: $DOMAIN
  PASSPORT_PROFILE_FIELD: $PASSPORT_PROFILE_FIELD
  FACEBOOK_CALLBACK_URL: $FACEBOOK_CALLBACK_URL
  PORT: $PORT
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
test:
  stage: test
  before_script:
    - npm install --skip-cleanup
  script:
    - npm run test:CI
