const moment = require('moment');

const createdAt = moment(new Date()).format('YYYY-MM-DD HH:mm:ss');
const updatedAt = createdAt;

module.exports = [
  {
    country_name: 'Uganda',
    country_code: '256',
    country_prefix: 'UG',
    country_currency: 'UGX',
    country_language: 'en',
    usd_rate: 3937.5,
    usd_support: 0,
    network_support: 3,
    createdAt,
    updatedAt,
  },
  {
    country_name: 'Democratic Republic of Congo',
    country_code: '243',
    country_prefix: 'DRC',
    country_currency: 'CDF',
    country_language: 'fr',
    usd_rate: 2100,
    usd_support: 1,
    network_support: 2,
    createdAt,
    updatedAt,
  },
  {
    country_name: 'Kenya',
    country_code: '254',
    country_prefix: 'KE',
    country_currency: 'KES',
    country_language: 'en',
    usd_rate: 118.65,
    usd_support: 0,
    network_support: 2,
    createdAt,
    updatedAt,
  },
  {
    country_name: 'Rwanda',
    country_code: '250',
    country_prefix: 'RW',
    country_currency: 'RWF',
    country_language: 'en',
    usd_rate: 1029,
    usd_support: 0,
    network_support: 3,
    createdAt,
    updatedAt,
  },
  {
    country_name: 'Burundi',
    country_code: '257',
    country_prefix: 'BI',
    country_currency: 'BIF',
    country_language: 'fr',
    usd_rate: 2100,
    usd_support: 0,
    network_support: 4,
    createdAt,
    updatedAt,
  },
  {
    country_name: 'Tanzania',
    country_code: '255',
    country_prefix: 'TZ',
    country_currency: 'TZS',
    country_language: 'en',
    usd_rate: 2441.25,
    usd_support: 1,
    network_support: 2,
    createdAt,
    updatedAt,
  },
  {
    country_name: 'Zambia',
    country_code: '260',
    country_prefix: 'ZM',
    country_currency: 'ZMW',
    country_language: 'en',
    usd_rate: 2100,
    usd_support: 0,
    network_support: 3,
    createdAt,
    updatedAt,
  },
  {
    country_name: 'Nigeria',
    country_code: '234',
    country_prefix: 'NG',
    country_currency: 'NGN',
    country_language: 'en',
    usd_rate: 975.0,
    usd_support: 0,
    network_support: 3,
    createdAt,
    updatedAt,
  },
  {
    country_name: 'Ghana',
    country_code: '233',
    country_prefix: 'GH',
    country_currency: 'GHS',
    country_language: 'en',
    usd_rate: 7.35,
    usd_support: 0,
    network_support: 3,
    createdAt,
    updatedAt,
  },
  {
    country_name: 'Senegal',
    country_code: '221',
    country_prefix: 'SN',
    country_currency: 'XOF',
    country_language: 'fr',
    usd_rate: 588,
    usd_support: 1,
    network_support: 4,
    createdAt,
    updatedAt,
  },
  {
    country_name: 'Cameroon',
    country_code: '237',
    country_prefix: 'CM',
    country_currency: 'XAF',
    country_language: 'fr',
    usd_rate: 588,
    usd_support: 0,
    network_support: 1,
    createdAt,
    updatedAt,
  },
  {
    country_name: 'Ivory Coast',
    country_code: '225',
    country_prefix: 'CV',
    country_currency: 'XOF',
    country_language: 'ft',
    usd_rate: 588,
    usd_support: 0,
    network_support: 1,
    createdAt,
    updatedAt,
  },
  {
    country_name: 'USA',
    country_code: '1',
    country_prefix: 'US',
    country_currency: 'USD',
    country_language: 'en',
    usd_rate: 1,
    usd_support: 0,
    network_support: 4,
    createdAt,
    updatedAt,
  },
  {
    country_name: 'Canada',
    country_code: '1',
    country_prefix: 'CA',
    country_currency: 'CAD',
    country_language: 'en',
    usd_rate: 1.48449,
    usd_support: 0,
    network_support: 4,
    createdAt,
    updatedAt,
  },
];
