export const ACCOUNT_AUTHENTIFICATED = 'ACCOUNT_AUTHENTIFICATED';
export const ACCOUNT_CREATED = 'ACCOUNT_CREATED';

export default {
  ACCOUNT_AUTHENTIFICATED: 'ACCOUNT_AUTHENTIFICATED',
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
};
