export const EMIT_ACCOUNT_AUTHENTIFICATED = 'ACCOUNT_AUTHENTIFICATED';
export const EMIT_ACCOUNT_CREATED = 'ACCOUNT_CREATED';

export default {
  EMIT_ACCOUNT_AUTHENTIFICATED: 'ACCOUNT_AUTHENTIFICATED',
  EMIT_ACCOUNT_CREATED: 'ACCOUNT_CREATED',
};
